FROM nginx:stable-alpine

ADD ./nginx.conf /etc/nginx/nginx.conf

RUN mkdir -p /var/www/html/backend

RUN addgroup -g 1000 symfony && adduser -G symfony -g symfony -s /bin/sh -D symfony

RUN chown symfony:symfony /var/www/html/backend


COPY default.conf.dev /etc/nginx/templates/default.conf.template
COPY docker-default.sh /

# Just in case the file mode was not properly set in Git
RUN chmod +x /docker-default.sh

# This will delegate to the original `docker-entrypoint.sh`
ENTRYPOINT ["/docker-default.sh"]

CMD ["nginx", "-g", "daemon off;"]