const userFields = [
  {
    labelText: "Name",
    labelFor: "name",
    labelAlignLeft: true,
    id: "name",
    name: "name",
    type: "text",
    autoComplete: "name",
    isRequired: true,
    placeholder: "Your name",
    css: "w-full h-10 px-3 text-base placeholder-gray-600 border rounded-lg focus:shadow-outline",
  },
  {
    labelText: "Email",
    labelFor: "email",
    labelAlignLeft: true,
    id: "email",
    name: "email",
    type: "email",
    autoComplete: "nemailame",
    isRequired: true,
    disable: true,
    placeholder: "Your Email Address",
    css: "w-full h-10 px-3 text-base placeholder-gray-600 border rounded-lg focus:shadow-outline",
  },
  {
    labelText: "House Number",
    labelFor: "house_number",
    labelAlignLeft: true,
    id: "house_number",
    name: "house_number",
    type: "text",
    autoComplete: "house_number",
    isRequired: true,
    placeholder: "Your house_number",
    css: "w-full h-10 px-3 text-base placeholder-gray-600 border rounded-lg focus:shadow-outline",
  },
  {
    labelText: "Address",
    labelFor: "address",
    labelAlignLeft: true,
    id: "address",
    name: "address",
    type: "text",
    autoComplete: "address",
    isRequired: true,
    placeholder: "Your address",
    css: "w-full h-10 px-3 text-base placeholder-gray-600 border rounded-lg focus:shadow-outline",
  },
  {
    labelText: "City",
    labelFor: "city",
    labelAlignLeft: true,
    id: "city",
    name: "city",
    type: "text",
    autoComplete: "city",
    isRequired: true,
    placeholder: "Your city",
    css: "w-full h-10 px-3 text-base placeholder-gray-600 border rounded-lg focus:shadow-outline",
  },
  {
    labelText: "Postcode",
    labelFor: "postcode",
    labelAlignLeft: true,
    id: "postcode",
    name: "postcode",
    type: "text",
    autoComplete: "postcode",
    isRequired: true,
    placeholder: "Your postcode",
    css: "w-full h-10 px-3 text-base placeholder-gray-600 border rounded-lg focus:shadow-outline",
  },
];
export { userFields };
